### ISSUE TITLE
Entries file must be created manually

### ISSUE THREAD

**Issue by tpoliaw** [cengels/dlog#1]
Installing (via cargo) and running `dlog start` gives a `no such file` error. I would expect the file to be created automatically if it does not exist. Interestingly, the `~/.local/share/dlog` firectory is created.

Creating the `entries` file fixed the problem but required reading through the source to see what the file should be called (and where it was looking).

**Comment by cengels** [comment]
Thanks for the report! I just released version [0.1.2](https://github.com/cengels/dlog/blob/master/CHANGELOG.md), which (among other things) includes a bugfix for this.

> I would expect the file to be created automatically if it does not exist.

When writing the file, yes, this is indeed what happens. The error in question, however, happened while attempting to read the file. That was an oversight on my part. dlog now appropriately falls back to an empty vector if it cannot find the entries file.
